### ISSUE TITLE
Feat: The error messages displayed after "start replay" need to be optimized.

### ISSUE THREAD

**Issue by lijing-22** [arextest/arex#224]
## Current Behavior

The error messages displayed after "start replay" are hard to understand.

![L4E1GB0P@T3%DZ(MB26KGVP](https://github.com/arextest/arex/assets/118187476/1e71aa81-aa40-4490-8d41-894caff605e9)
![image](https://github.com/arextest/arex/assets/118187476/7e1b0c0b-de58-408f-a8bc-6543410ac893)

## Expected Behavior
- If there are no recorded cases: no recorded cases found, please make sure there are traffic requests in the application before replaying or change the time range.
- If the target host is incorrect: incorrect target host, please enter the correct target host.

**Comment by QizhengMo** [comment]
| Error Code | Reason |Error message|
| ------------| ------- |-------------- |
| 001  | Another plan is been creating for the same app  |Content Cell  |
| 002  | The requested replay type passed by the front end is not supported, might be caused by unmatched backend services |Content Cell  |
| 101  |  Not service found for the app, might be caused by no case recorded |Content Cell  |
| 102  |  Invalid or empty source type |Content Cell  |
| 103  |  Invalid case range, start time must be before end time  |Content Cell  |
| 104  |  Requested replay env unable to load active instance, might be caused by agent failing to init or network issue |Content Cell  |
| 104 |  Requested source compare env unable to load active instance, might be caused by agent failing to init or network issue   |Content Cell  |
| 200  |  Can not find any case to replay from the requested range |Content Cell  |
| 300  |  DB error, might be caused by invalid connection string |Content Cell  |
| 500  |  Unchecked exception |Content Cell  |

**Comment by 1pone** [comment]
https://github.com/arextest/arex/pull/262

**Comment by fly-1999** [comment]
#271
